version: '2'
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
      - "443:443"
    links:
      - php
    volumes:
      - ./sites:/etc/nginx/conf.d
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www

  php:
    build: .
    working_dir: /var/www/default
    volumes:
      - ./www:/var/www